import environs

ENV = environs.Env()
ENV.read_env(".env")

# HASHIDS CONFIGURATION
HASHIDS_SALT = ENV("HASHIDS_SALT", default="90fce962aa905e94c22c97efbe7326d2")
HASHIDS_MIN_LENGTH = 6

# CASSANDRA CONFIGURATION
CASSANDRA_CONTACT_POINTS = ENV.list("CASSANDRA_CONTACT_POINTS")
CASSANDRA_PORT = ENV("CASSANDRA_PORT", default=9042)
CASSANDRA_KEYSPACE = ENV("CASSANDRA_KEYSPACE", default="events")
CASSANDRA_USERNAME = ENV("CASSANDRA_USERNAME", default="cassandra")
CASSANDRA_PASSWORD = ENV("CASSANDRA_PASSWORD", default="")

# KAFKA CONFIGURATION
KAFKA_BOOTSTRAP_SERVERS = ENV.list("KAFKA_BOOTSTRAP_SERVERS", default=["127.0.0.1:9092"])
