apiVersion: skaffold/v2beta19
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: affo/auth
      context: py/
      docker:
        dockerfile: services/auth/Dockerfile
    - image: affo/users
      context: py/
      docker:
        dockerfile: services/users/Dockerfile
    - image: affo/billing
      context: py/
      docker:
        dockerfile: services/billing/Dockerfile
    - image: affo/deeplinks
      context: py/
      docker:
        dockerfile: services/deeplinks/Dockerfile
    - image: affo/events
      context: py/
      docker:
        dockerfile: services/events/Dockerfile
    - image: affo/stats-aggregator
      context: py/
      docker:
        dockerfile: services/stats-aggregator/Dockerfile
    - image: affo/stats
      context: py/
      docker:
        dockerfile: services/stats/Dockerfile
    - image: affo/revenue
      context: py/
      docker:
        dockerfile: services/revenue/Dockerfile
    - image: affo/ui-affo
      context: ui/affo
    - image: trymarqet/orders
      context: py/
      docker:
        dockerfile: services/orders/Dockerfile
deploy:
  helm:
    releases:
      - name: affo
        namespace: affo
        chartPath: deployments/helm/affo
        imageStrategy:
          helm: {}
        setValueTemplates:
          image.tag: "{{ .DIGEST_HEX }}"
        valuesFiles:
          - examples/helm/affo/values.dev.yaml
          - examples/helm/affo/secrets.dev.yaml
        wait: true
      - name: trymarqet
        namespace: trymarqet
        chartPath: deployments/helm/trymarqet
        imageStrategy:
          helm: {}
        setValueTemplates:
          image.tag: "{{ .DIGEST_HEX }}"
        valuesFiles:
          - examples/helm/trymarqet/values.dev.yaml
          - examples/helm/trymarqet/secrets.dev.yaml
        wait: true
