apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "trymarqet.fullname" . }}
  namespace: {{ include "trymarqet.namespace" . }}
  labels:
    {{- include "trymarqet.labels" . | nindent 4 }}
spec:
  hosts:
  - trymarqet.arch.homework
  gateways:
  - {{ include "trymarqet.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /orders/
    route:
    - destination:
        port:
          number: 80
        host: {{ include "trymarqet.fullname" . }}-orders
