apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "affo.fullname" . }}-jwt-authz-users
  namespace: {{ include "affo.namespace" . }}
  labels:
    {{- include "affo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: users
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["affo/users"]
    to:
    - operation:
        paths: ["/user/*", "/logout/"]
  - to:
    - operation:
        paths: ["/login/", "/register/"]
  - from:
    - source:
        namespaces: [{{ include "affo.namespace" . }}]
    to:
    - operation:
        paths: ["*"]