import environs

ENV = environs.Env()
ENV.read_env(".env")

# CASSANDRA CONFIGURATION
CASSANDRA_CONTACT_POINTS = ENV.list("CASSANDRA_CONTACT_POINTS")
CASSANDRA_PORT = ENV("CASSANDRA_PORT", default=9042)
CASSANDRA_KEYSPACE = ENV("CASSANDRA_KEYSPACE", default="stats")
CASSANDRA_USERNAME = ENV("CASSANDRA_USERNAME", default="cassandra")
CASSANDRA_PASSWORD = ENV("CASSANDRA_PASSWORD", default="")
